# @name Signup
POST http://localhost:3333/user/signup
content-type: application/json

{
  "name": "John",
  "email": "email1@email.com",
  "password": "123456"
}

###

# @name Signin
POST http://localhost:3333/user/signin
content-type: application/json

{
  "email": "email1@email.com",
  "password": "123456"
}

###

# @name Me
GET http://localhost:3333/user/me
content-type: application/json
Authorization: Bearer xxx

###

# @name CreateMeal
POST http://localhost:3333/meals
content-type: application/json
Authorization: Bearer xxx

{
  "name": "Alface 3",
  "description": "De feira no domingo",
  "hours": 0,
  "isDiet": true
}

###

# @name GetMealsList
GET http://localhost:3333/meals/list
content-type: application/json
Authorization: Bearer xxx

###

# @name UpdateMeal
PATCH http://localhost:3333/meals/6636b7e5-9148-42ab-be91-51b70098b7e2
content-type: application/json
Authorization: Bearer xxx

{
  "name": "Pastel 2",
}

###

# @name DeleteMeal
DELETE http://localhost:3333/meals/6636b7e5-9148-42ab-be91-51b70098b7e2
content-type: application/json
Authorization: Bearer xxx

###

# @name GetMeal
GET http://localhost:3333/meals/c885c491-e8c8-4d36-8377-4c2cbdf1237f
content-type: application/json
Authorization: Bearer xxx

###

# @name MetricsCount
GET http://localhost:3333/metrics/count
Authorization: Bearer xxx

###

# @name MetricsIsDiet
GET http://localhost:3333/metrics?isDiet=true
Authorization: Bearer xxx

###

# @name MetricsBestSequence
GET http://localhost:3333/metrics/best-sequence
Authorization: Bearer xxx

###