# @name user/signup
POST http://localhost:3333/user/signup
content-type: application/json

{
  "name": "John",
  "email": "email1@email.com",
  "password": "123456"
}

###

# @name user/signin
POST http://localhost:3333/user/signin
content-type: application/json

{
  "email": "email1@email.com",
  "password": "123456"
}

###

# @name user/me
GET http://localhost:3333/user/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjcwN2E2Mi04OGY0LTRiYzQtOTMzNS0yZmZiYzczZjRkNmQiLCJpYXQiOjE2OTkyODk5MjgsImV4cCI6MTY5OTI5MDA0OH0.T17p8FS0VdbngDSsuFfthHH1VWM1PlsWJqHnEv0wsI0

###

# @name meals
POST http://localhost:3333/meals
content-type: application/json

{
  "name": "Pastel",
  "description": "De feira no domingo",
  "hours": 0,
  "isDiet": false
}

###

# @name meals
PATCH http://localhost:3333/meals
content-type: application/json

{
  "name": "Pastel",
}

###

# @name meals
DELETE http://localhost:3333/meals
content-type: application/json

{
  "id": "123",
}

###

# @name metrics/count
GET http://localhost:3333/metrics/count

###

# @name metrics/:isDiet
GET http://localhost:3333/metrics?isDiet=true

###

# @name metrics/best-sequence
GET http://localhost:3333/metrics/best-sequence

###